---
name: "Session Cleaner"
guid: "EC9E2A74-1311-4A14-B302-158E3D95FD1D"
version: "2.0.0.0"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "crobibero"
overview: "Removes old sessions (devices)."
description: >
  Removes old sessions (devices).

category: "General"
artifacts:
  - "Jellyfin.Plugin.SessionCleaner.dll"
changelog: |-
  - chore(deps): bump StyleCop.Analyzers from 1.2.0-beta.376 to 1.2.0-beta.406 (#6) @dependabot
  - Use meta ci (#5) @crobibero
  - 10.8 support (#2) @crobibero
